  
---
- name: install apache is node is a RedHat, CentOS or Fedora machine
  hosts: all
    tasks:
      - name: restart httpd
        service: name=httpd state=restarted
        when: ansible_host == "192.168.2.106"
