---
- name: update apache if date is 20
  hosts: all
  vars:
    - date: 20
  tasks:
    - name: update apache
      yum:
        name: httpd
        state: latest
      when: date == 20
#This playbook will run since date is 20.
