---
- name: using the cron module
  hosts: all
  tasks:
          - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
            cron:
                name: "check dirs"
                minute: "0"
                hour: "5,2"
                job: "ls -alh > /tmp/ls.txt"
