---
- name: parted module for storage
  hosts: all
  tasks:
          - name: new 10GB partition
            parted:
                    device: /dev/sdb
                    number: 1
                    state: present
                    part_end: 10GB
